In [1]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D,Conv2DTranspose
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.preprocessing import image
from tensorflow.python.keras.utils import layer_utils
from tensorflow.python.keras.utils.data_utils import get_file
from tensorflow.keras.applications.imagenet_utils import preprocess_input
from tensorflow.python.keras.utils.vis_utils import model_to_dot
from tensorflow.keras.utils import plot_model
from tensorflow.keras.initializers import glorot_uniform

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Softmax,Activation,Dense,ZeroPadding2D,Convolution2D
from tensorflow.python.keras.utils.np_utils import to_categorical

from tensorflow.keras.datasets import mnist
from sklearn.metrics import recall_score,f1_score,precision_score
from tensorflow.keras.optimizers import SGD

#import pydot
#from IPython.display import SVG
#import scipy.misc
from matplotlib.pyplot import imshow
import tensorflow.keras.backend as K
K.set_image_data_format('channels_last')
K.set_learning_phase(1)
import os
#import resnets_utils
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"#选择哪一块gpu,如果是-1，就是调用cpu
config = tf.compat.v1.ConfigProto()#对session进行参数配置
config.allow_soft_placement=True # 如果你指定的设备不存在，允许TF自动分配设备
config.gpu_options.per_process_gpu_memory_fraction=0.7#分配百分之七十的显存给程序使用，避免内存溢出，可以自己调整
config.gpu_options.allow_growth = True#按需分配显存，这个比较重要
session = tf.compat.v1.Session(config=config)

E:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\backend.py:434: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


In [6]:
NOISE_E=load_model('NLE.h5')
model_LC=load_model('Classifier.h5')
model_GC=load_model('SCN.h5')
model_Learn=load_model('Feature_extraction.h5')
model_Learnfeature=Model(inputs=model_Learn.input,outputs=model_Learn.layers[122].output)

In [10]:
y=np.load("TESTLable.npy")

Aimages4=np.load("TEST4DB.npy")
Aimages2=np.load("TEST2DB.npy")
Aimages0=np.load("TEST0DB.npy")
Aimagesf2=np.load("TESTf2DB.npy")
Aimagesf4=np.load("TESTf4DB.npy")
Aimagesf6=np.load("TESTf6DB.npy")
Aimagesf8=np.load("TESTf8DB.npy")
Aimagesf10=np.load("TESTf10DB.npy")
Aimagesf12=np.load("TESTf12DB.npy")
Aimagesf14=np.load("TESTf14DB.npy")
Aimagesf16=np.load("TESTf16DB.npy")

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
images4   = model_Learnfeature.predict(Aimages4   /255.0)
aaimages4=NOISE_E.predict(Aimages4   /255.0)

images2   = model_Learnfeature.predict(Aimages2   /255.0)
aaimages2=NOISE_E.predict(Aimages2   /255.0)

images0   = model_Learnfeature.predict(Aimages0   /255.0)
aaimages0=NOISE_E.predict(Aimages0   /255.0)

imagesf2  = model_Learnfeature.predict(Aimagesf2  /255.0)
aaimagesf2=NOISE_E.predict(Aimagesf2   /255.0)

imagesf4  = model_Learnfeature.predict(Aimagesf4  /255.0)
aaimagesf4=NOISE_E.predict(Aimagesf4   /255.0)

imagesf6  = model_Learnfeature.predict(Aimagesf6  /255.0)
aaimagesf6=NOISE_E.predict(Aimagesf6   /255.0)

imagesf8  = model_Learnfeature.predict(Aimagesf8  /255.0)
aaimagesf8=NOISE_E.predict(Aimagesf8   /255.0)

imagesf10 = model_Learnfeature.predict(Aimagesf10 /255.0)
aaimagesf10=NOISE_E.predict(Aimagesf10   /255.0)

imagesf12 = model_Learnfeature.predict(Aimagesf12 /255.0)
aaimagesf12=NOISE_E.predict(Aimagesf12   /255.0)

imagesf14 = model_Learnfeature.predict(Aimagesf14 /255.0)
aaimagesf14=NOISE_E.predict(Aimagesf14   /255.0)

imagesf16 = model_Learnfeature.predict(Aimagesf16 /255.0)
aaimagesf16=NOISE_E.predict(Aimagesf16   /255.0)


In [11]:
aa=aaimages4
ff=images4
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'4dB')
print(confusion_matrix(y,x))

1.0 4dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [12]:
aa=aaimages2
ff=images2
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'2dB')
print(confusion_matrix(y,x))

1.0 2dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [13]:
aa=aaimages0
ff=images0
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'0dB')
print(confusion_matrix(y,x))

1.0 0dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [14]:
aa=aaimagesf2
ff=imagesf2
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-2dB')
print(confusion_matrix(y,x))

1.0 -2dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [23]:
aa=aaimagesf4
ff=imagesf4
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-4dB')
print(confusion_matrix(y,x))

0.998 -4dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   2   0   0   0   0   0   0   0  98]]


In [22]:
aa=aaimagesf6
ff=imagesf6
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-6dB')
print(confusion_matrix(y,x))

0.996 -6dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0 100   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0   4   0   0   0   0   0   0   0  96]]


In [17]:
aa=aaimagesf8
ff=imagesf8
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-8dB')
print(confusion_matrix(y,x))

0.96 -8dB
[[100   0   0   0   0   0   0   0   0   0]
 [  0  85   0   0   0   0   0   0   0  15]
 [  0   0 100   0   0   0   0   0   0   0]
 [  0   0   0  99   1   0   0   0   0   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0  99   1   0   0   0]
 [  0   0   0   0   0   2  96   2   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0   0   0 100   0]
 [  0  19   0   0   0   0   0   0   0  81]]


In [18]:
aa=aaimagesf10
ff=imagesf10
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)

In [19]:
aa=aaimagesf12
ff=imagesf12
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-12dB')
print(confusion_matrix(y,x))

0.737 -12dB
[[78  0  0  0  0  0  0  0 22  0]
 [ 0 55  4  0  3  0  1  2  0 35]
 [ 1  0 96  0  2  0  0  0  1  0]
 [ 0  1  0 72 13  4  7  1  1  1]
 [ 0  4  3  2 86  0  0  0  4  1]
 [ 0  0  0  1  0 83 16  0  0  0]
 [ 0  0  1  2  0 20 71  6  0  0]
 [ 0  1  1  2  5  1 10 78  0  2]
 [14  0  0  0  3  0  0  0 83  0]
 [ 0 40  1  1 15  0  0  3  5 35]]


In [20]:
aa=aaimagesf14
ff=imagesf14
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)
print(accuracy_test4,'-14dB')
print(confusion_matrix(y,x))

0.526 -14dB
[[51  0  2  3  4  1  0  0 37  2]
 [ 0 36  5  4 14  0  3  1  5 32]
 [ 1  4 75  3 11  1  1  1  1  2]
 [ 0  0  3 38 43  2  5  2  7  0]
 [ 1  4  3  9 71  1  3  3  3  2]
 [ 1  1  0  8  1 60 23  3  2  1]
 [ 1  0  3 12  6 14 45 13  5  1]
 [ 0  4  5  3  8  2  4 58  9  7]
 [15  3  3  0  9  0  1  4 64  1]
 [ 1 29  5  1 17  3  2  9  5 28]]


In [21]:
aa=aaimagesf16
ff=imagesf16
x=np.zeros((1000,1), dtype='uint8')
for i in range(1000):
    a1=aa[i,1]
    a2=aa[i,0]
    if a1 < a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_LC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
    if a1 >= a2:
        f2=ff[i]
        f2=f2.reshape(1,2048)
        x2=model_GC.predict(f2)
        x[i]=np.argmax(x2,axis=1)
accuracy_test4 = accuracy_score(y,x)